const BASE = "/api/v1/agent-registration";
const OTP_STORAGE_KEY = "pol_registration_otp";

export type AgentRegistrationStatus = "Draft" | "Pending" | "Approved" | "Rejected";
export type AgentRegistrationNextAction = "submit" | "wait" | "login";
export type AgentAttemptStatus = "Pending" | "Approved" | "Rejected";

export interface AgentRegistrationView { registrationId: string; merchantId: string; status: AgentRegistrationStatus; currentAttemptNo: number; currentAttemptId: string | null; rejectionReason: string | null; version: number; saleCode?: string; email?: string; phoneNumber?: string; profile?: Record<string, unknown>; hasPhoto?: boolean; hasKycPhoto?: boolean; phoneVerified?: boolean; }
export interface AgentRegistrationAttemptView { attemptId: string; attemptNo: number; status: AgentAttemptStatus; submittedAt: string; rejectionReason: string | null; version: number; decidedAt: string | null; hasPhoto?: boolean; hasKycPhoto?: boolean; }
export interface AgentRegistrationCase { registration: AgentRegistrationView; nextAction: AgentRegistrationNextAction; currentAttempt: AgentRegistrationAttemptView | null; etag: string | null; }
export interface AgentRegistrationDraft { saleCode: string; email: string; phoneNumber: string; profile: Record<string, unknown>; }
export interface ContactVerification { verificationId: string; expiresAt: string; resendAvailableAt: string; }
export type PendingVerification = ContactVerification;
export type AgentRegistrationResult<T> = { ok: true; value: T } | { ok: false; status: number; code: string | null; title: string | null };

export function normalizeAttemptStatus(raw: string): AgentAttemptStatus { return raw.toUpperCase() === "APPROVED" ? "Approved" : raw.toUpperCase() === "REJECTED" ? "Rejected" : "Pending"; }
const networkError = (): AgentRegistrationResult<never> => ({ ok: false, status: 0, code: "network", title: null });
async function error<T>(res: Response): Promise<AgentRegistrationResult<T>> { try { const body = await res.json() as { code?: string; title?: string; extensions?: { code?: string } }; return { ok: false, status: res.status, code: body.code ?? body.extensions?.code ?? null, title: body.title ?? null }; } catch { return { ok: false, status: res.status, code: null, title: null }; } }
function parseCase(body: { registration: AgentRegistrationView; nextAction: AgentRegistrationNextAction; currentAttempt: (AgentRegistrationAttemptView & { status: string }) | null }, res: Response): AgentRegistrationCase { return { registration: body.registration, nextAction: body.nextAction, currentAttempt: body.currentAttempt ? { ...body.currentAttempt, status: normalizeAttemptStatus(body.currentAttempt.status) } : null, etag: res.headers.get("ETag") }; }
async function request<T>(path: string, init: RequestInit, success: number, parse: (res: Response) => Promise<T>): Promise<AgentRegistrationResult<T>> { try { const res = await fetch(path, { credentials: "include", ...init }); return res.status === success ? { ok: true, value: await parse(res) } : error(res); } catch { return networkError(); } }

export async function getAgentRegistration(): Promise<AgentRegistrationResult<AgentRegistrationCase | null>> { try { const res = await fetch(BASE, { credentials: "include", cache: "no-store" }); if (res.status === 404) return { ok: true, value: null }; return res.status === 200 ? { ok: true, value: parseCase(await res.json(), res) } : error(res); } catch { return networkError(); } }
export function saveAgentRegistrationDraft(draft: AgentRegistrationDraft, etag: string | null): Promise<AgentRegistrationResult<AgentRegistrationCase>> { const headers: Record<string,string> = { "Content-Type": "application/json" }; if (etag) headers["If-Match"] = etag; return request(BASE, { method: "PUT", headers, body: JSON.stringify(draft) }, 200, async r => parseCase(await r.json(), r)); }
export function uploadAgentRegistrationPhotos(photo: File, kycPhoto: File | null): Promise<AgentRegistrationResult<{ etag: string | null }>> { const body = new FormData(); body.append("photo", photo); if (kycPhoto) body.append("kycPhoto", kycPhoto); return request(`${BASE}/photos`, { method: "PUT", body }, 200, async r => ({ etag: r.headers.get("ETag") })); }
export function submitAgentRegistration(etag: string, idempotencyKey: string): Promise<AgentRegistrationResult<{ registration: AgentRegistrationView; attempt: AgentRegistrationAttemptView; replayed: boolean; etag: string | null }>> { return request(`${BASE}/submissions`, { method: "POST", headers: { "Content-Type": "application/json", "If-Match": etag, "Idempotency-Key": idempotencyKey }, body: "{}" }, 201, async r => { const body = await r.json() as { registration: AgentRegistrationView; attempt: AgentRegistrationAttemptView & { status: string }; replayed: boolean }; return { registration: body.registration, attempt: { ...body.attempt, status: normalizeAttemptStatus(body.attempt.status) }, replayed: body.replayed, etag: r.headers.get("ETag") }; }); }
export function requestContactVerification(): Promise<AgentRegistrationResult<ContactVerification>> { return request(`${BASE}/contact-verifications`, { method: "POST" }, 202, r => r.json()); }
export function confirmContactVerification(id: string, code: string): Promise<AgentRegistrationResult<{ verificationId: string; confirmedAt: string; registration: AgentRegistrationView; etag: string | null }>> { return request(`${BASE}/contact-verifications/${encodeURIComponent(id)}/confirm`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code }) }, 200, async r => ({ ...(await r.json() as { verificationId: string; confirmedAt: string; registration: AgentRegistrationView }), etag: r.headers.get("ETag") })); }

export type RegistrationUiState = { kind: "form" } | { kind: "form-prefill"; rejected: boolean } | { kind: "verify" } | { kind: "ready" } | { kind: "wait" } | { kind: "approved" } | { kind: "error" };
export function resolveRegistrationUiState(result: AgentRegistrationResult<AgentRegistrationCase | null> | AgentRegistrationCase | null): RegistrationUiState { if (result === null) return { kind: "form" }; if (!("ok" in result)) { const legacy = result; if (legacy.nextAction === "login") return { kind: "approved" }; if (legacy.nextAction === "wait") return { kind: "wait" }; return !legacy.registration.hasPhoto ? { kind: "form-prefill", rejected: legacy.registration.rejectionReason !== null } : legacy.registration.phoneVerified ? { kind: "ready" } : { kind: "verify" }; } if (!result.ok) return result.status === 401 ? { kind: "form" } : { kind: "error" }; const value = result.value; if (!value) return { kind: "form" }; if (value.nextAction === "login") return { kind: "approved" }; if (value.nextAction === "wait") return { kind: "wait" }; if (!value.registration.hasPhoto) return { kind: "form-prefill", rejected: value.registration.rejectionReason !== null }; return value.registration.phoneVerified ? { kind: "ready" } : { kind: "verify" }; }
export function registrationRedirect(route: "form" | "verify" | "pending", state: RegistrationUiState): string | null { if (state.kind === "wait") return route === "pending" ? null : "/register/pending"; if ((state.kind === "verify" || state.kind === "ready") && route === "pending") return "/register/verify"; if ((state.kind === "form" || state.kind === "form-prefill" || state.kind === "approved") && route !== "form") return "/register"; return null; }
export type RegisterField = "photo" | "producerCode" | "phoneNumber" | "email" | "form";
export type SubmitErrorAction = { kind: "field"; field: RegisterField; message: string } | { kind: "redirect"; reason: string } | { kind: "reload" } | { kind: "retry-refetch" } | { kind: "retry-newkey" } | { kind: "verify-required" } | { kind: "cooldown" } | { kind: "error"; message: string };
const GENERIC_ERROR = "เกิดข้อผิดพลาด กรุณาลองใหม่";
export function classifySubmitError(status: number, code: string | null, title: string | null): SubmitErrorAction { if (status === 401) return { kind: "redirect", reason: "registration-session-expired" }; if (status === 413) return { kind: "field", field: "photo", message: "ไฟล์รูปมีขนาดใหญ่เกิน 2 MB" }; if (status === 503) return { kind: "error", message: "ระบบยังไม่พร้อมส่ง SMS" }; if (status === 400) { if (code === "phone_verification_required") return { kind: "verify-required" }; if (code === "phone_invalid") return { kind: "field", field: "phoneNumber", message: "กรุณากรอกเบอร์มือถือไทย 10 หลัก เช่น 0812345678" }; if (code === "photo_required") return { kind: "field", field: "photo", message: "กรุณาแนบรูปถ่ายตัวแทน" }; if (code === "validation_failed") return { kind: "field", field: "form", message: title ?? "ข้อมูลไม่ถูกต้อง กรุณาตรวจสอบ" }; } if (status === 409) { if (code === "email_already_registered") return { kind: "field", field: "email", message: "อีเมลนี้ลงทะเบียนแล้ว กรุณาเข้าสู่ระบบ" }; if (code === "verification_cooldown" || code === "verification_send_limit") return { kind: "cooldown" }; if (code === "phone_already_verified" || code === "registration_pending") return { kind: "reload" }; if (code === "state_conflict") return { kind: "retry-refetch" }; if (code === "idempotency_conflict") return { kind: "retry-newkey" }; } return { kind: "error", message: GENERIC_ERROR }; }
export function classifyConfirmError(status: number, code: string | null): SubmitErrorAction { if (status === 401) return { kind: "redirect", reason: "registration-session-expired" }; if (status === 400 && code === "verification_code_invalid") return { kind: "field", field: "form", message: "รหัสยืนยันไม่ถูกต้อง" }; if (status === 409 && code === "verification_expired") return { kind: "field", field: "form", message: "รหัสยืนยันหมดอายุ" }; if (status === 409 && code === "verification_attempts_exceeded") return { kind: "field", field: "form", message: "กรอกรหัสผิดเกินจำนวนที่กำหนด" }; if (status === 409) return { kind: "reload" }; return { kind: "error", message: GENERIC_ERROR }; }
export interface SubmitContext { etag: string; idempotencyKey: string; }
export type SubmitOutcome = { kind: "success" } | { kind: "reload" } | { kind: "field"; field: RegisterField; message: string } | { kind: "redirect"; reason: string } | { kind: "retryable" } | { kind: "verify" } | { kind: "error"; message: string };
export interface SubmitResult { outcome: SubmitOutcome; ctx?: SubmitContext; verification?: ContactVerification; }
const key = () => crypto.randomUUID();
export async function submitWithRetry(etag: string, idempotencyKey = key()): Promise<SubmitResult> { const result = await submitAgentRegistration(etag, idempotencyKey); const ctx = { etag, idempotencyKey }; if (result.ok) return { outcome: { kind: "success" }, ctx }; if (result.status === 0) return { outcome: { kind: "retryable" }, ctx }; const action = classifySubmitError(result.status, result.code, result.title); if (action.kind === "verify-required") return { outcome: { kind: "verify" }, ctx }; if (action.kind === "reload" || action.kind === "retry-refetch" || action.kind === "retry-newkey" || action.kind === "cooldown") return { outcome: { kind: "reload" }, ctx }; return { outcome: action, ctx }; }
export async function startRegistration(params: { draft: AgentRegistrationDraft; photo: File; kycPhoto: File | null; etag: string | null }): Promise<SubmitResult> { const draft = await saveAgentRegistrationDraft(params.draft, params.etag); if (!draft.ok) return { outcome: actionToOutcome(classifySubmitError(draft.status, draft.code, draft.title)) }; const photos = await uploadAgentRegistrationPhotos(params.photo, params.kycPhoto); if (!photos.ok) return { outcome: actionToOutcome(classifySubmitError(photos.status, photos.code, photos.title)) }; if (!photos.value.etag) return { outcome: { kind: "error", message: GENERIC_ERROR } }; if (draft.value.registration.phoneVerified) return submitWithRetry(photos.value.etag); const otp = await requestContactVerification(); if (otp.ok) return { outcome: { kind: "verify" }, verification: otp.value }; return { outcome: actionToOutcome(classifySubmitError(otp.status, otp.code, otp.title)) }; }
function actionToOutcome(action: SubmitErrorAction): SubmitOutcome { if (action.kind === "verify-required") return { kind: "verify" }; if (action.kind === "reload" || action.kind === "retry-refetch" || action.kind === "retry-newkey" || action.kind === "cooldown") return { kind: "reload" }; return action; }
export async function confirmAndSubmit(id: string, code: string): Promise<SubmitResult> { const confirmed = await confirmContactVerification(id, code); if (!confirmed.ok) return { outcome: actionToOutcome(classifyConfirmError(confirmed.status, confirmed.code)) }; if (!confirmed.value.etag) return { outcome: { kind: "error", message: GENERIC_ERROR } }; return submitWithRetry(confirmed.value.etag); }
/** compatibility alias สำหรับ consumer เก่าระหว่าง migration; behavior ใหม่เริ่ม OTP ก่อน submit. */
export const submitNew = startRegistration;
export const retrySubmit = (ctx: SubmitContext) => submitWithRetry(ctx.etag, ctx.idempotencyKey);
export function readPendingVerification(): PendingVerification | null { try { const raw = sessionStorage.getItem(OTP_STORAGE_KEY); return raw ? JSON.parse(raw) as PendingVerification : null; } catch { return null; } }
export function writePendingVerification(value: PendingVerification): void { sessionStorage.setItem(OTP_STORAGE_KEY, JSON.stringify(value)); }
export function resendCooldownSeconds(resendAvailableAt: string, now = Date.now()): number { return Math.max(0, Math.ceil((new Date(resendAvailableAt).getTime() - now) / 1000)); }
