import { afterEach, describe, expect, it, vi } from "vitest";
import { classifyConfirmError, classifySubmitError, confirmAndSubmit, getAgentRegistration, registrationRedirect, resendCooldownSeconds, resolveRegistrationUiState, startRegistration, type AgentRegistrationCase, type AgentRegistrationDraft, type AgentRegistrationView } from "./agent-registration";

const registration: AgentRegistrationView = { registrationId: "r", merchantId: "m", status: "Draft", currentAttemptNo: 0, currentAttemptId: null, rejectionReason: null, version: 1, hasPhoto: true, phoneVerified: false };
const draft: AgentRegistrationDraft = { saleCode: "sale", email: "a@example.test", phoneNumber: "0812345678", profile: {} };
const photo = new File(["x"], "photo.jpg", { type: "image/jpeg" });
afterEach(() => vi.unstubAllGlobals());
function stub(routes: Record<string, (init: RequestInit) => Response>) { const mock = vi.fn(async (url: string, init: RequestInit = {}) => routes[`${init.method ?? "GET"} ${url}`]!(init)); vi.stubGlobal("fetch", mock); return mock; }
const json = (body: unknown, status = 200, etag = '"v1"') => new Response(JSON.stringify(body), { status, headers: { ETag: etag } });

describe("OTP registration flow", () => {
  it("anonymous GET 401 resolves to blank form, while other failure is error", async () => { expect(resolveRegistrationUiState({ ok: false, status: 401, code: null, title: null })).toEqual({ kind: "form" }); expect(resolveRegistrationUiState({ ok: false, status: 500, code: null, title: null })).toEqual({ kind: "error" }); });
  it("PUT draft -> photos -> contact verification 202; all requests use relative same-origin credentials", async () => { const mock = stub({ "PUT /api/v1/agent-registration": () => json({ registration, nextAction: "submit", currentAttempt: null }), "PUT /api/v1/agent-registration/photos": () => json({}), "POST /api/v1/agent-registration/contact-verifications": () => json({ verificationId: "v", expiresAt: "2026-01-01T00:00:00Z", resendAvailableAt: "2025-12-31T23:59:00Z" }, 202) }); const result = await startRegistration({ draft, photo, kycPhoto: null, etag: null }); expect(result.outcome).toEqual({ kind: "verify" }); expect(result.verification?.verificationId).toBe("v"); expect(mock.mock.calls.map(([u, i]) => `${i?.method} ${u}`)).toEqual(["PUT /api/v1/agent-registration", "PUT /api/v1/agent-registration/photos", "POST /api/v1/agent-registration/contact-verifications"]); for (const [, init] of mock.mock.calls) expect(init?.credentials).toBe("include"); });
  it("confirm uses returned ETag for submission", async () => { const mock = stub({ "POST /api/v1/agent-registration/contact-verifications/v/confirm": () => json({ verificationId: "v", confirmedAt: "now", registration: { ...registration, phoneVerified: true } }, 200, '"confirmed"'), "POST /api/v1/agent-registration/submissions": init => { expect(new Headers(init.headers).get("If-Match")).toBe('"confirmed"'); return json({ registration, attempt: { attemptId: "a", attemptNo: 1, status: "PENDING", submittedAt: "now", rejectionReason: null, version: 1, decidedAt: null }, replayed: false }, 201); } }); await expect(confirmAndSubmit("v", "123456")).resolves.toMatchObject({ outcome: { kind: "success" } }); expect(mock).toHaveBeenCalledTimes(2); });
  it("resolver and redirect table preserve pending/verify paths", () => { const pending: AgentRegistrationCase = { registration, nextAction: "wait", currentAttempt: null, etag: '"v"' }; expect(resolveRegistrationUiState({ ok: true, value: pending })).toEqual({ kind: "wait" }); expect(registrationRedirect("form", { kind: "wait" })).toBe("/register/pending"); expect(registrationRedirect("pending", { kind: "verify" })).toBe("/register/verify"); expect(registrationRedirect("verify", { kind: "form" })).toBe("/register"); });
  it("maps phone validation and OTP errors to observable UI actions", () => { expect(classifySubmitError(400, "phone_invalid", null)).toMatchObject({ kind: "field", field: "phoneNumber", message: "กรุณากรอกเบอร์มือถือไทย 10 หลัก เช่น 0812345678" }); expect(classifySubmitError(409, "email_already_registered", null)).toMatchObject({ field: "email" }); expect(classifyConfirmError(400, "verification_code_invalid")).toMatchObject({ kind: "field" }); expect(classifyConfirmError(409, "verification_expired")).toMatchObject({ kind: "field" }); expect(resendCooldownSeconds("2025-01-01T00:00:10Z", Date.parse("2025-01-01T00:00:00Z"))).toBe(10); });
  it("GET retains cookie credentials and ETag", async () => { const mock = stub({ "GET /api/v1/agent-registration": () => json({ registration, nextAction: "submit", currentAttempt: null }) }); const result = await getAgentRegistration(); expect(result.ok).toBe(true); expect(mock.mock.calls[0]![1]?.credentials).toBe("include"); });
});
