/** Phone country calling codes (ISO 3166-1 alpha-2, lowercase for flagcdn) + dial code. */
export interface PhoneCountry {
  name: string;
  iso2: string;
  dialCode: string;
}

export const DEFAULT_PHONE_ISO = "us";

export const PHONE_COUNTRIES: PhoneCountry[] = [
  { name: "Andorra", iso2: "ad", dialCode: "376" },
  { name: "United Arab Emirates", iso2: "ae", dialCode: "971" },
  { name: "Afghanistan", iso2: "af", dialCode: "93" },
  { name: "Antigua and Barbuda", iso2: "ag", dialCode: "1-268" },
  { name: "Anguilla", iso2: "ai", dialCode: "1-264" },
  { name: "Albania", iso2: "al", dialCode: "355" },
  { name: "Armenia", iso2: "am", dialCode: "374" },
  { name: "Angola", iso2: "ao", dialCode: "244" },
  { name: "Antarctica", iso2: "aq", dialCode: "672" },
  { name: "Argentina", iso2: "ar", dialCode: "54" },
  { name: "American Samoa", iso2: "as", dialCode: "1-684" },
  { name: "Austria", iso2: "at", dialCode: "43" },
  { name: "Australia", iso2: "au", dialCode: "61" },
  { name: "Aruba", iso2: "aw", dialCode: "297" },
  { name: "Åland Islands", iso2: "ax", dialCode: "358" },
  { name: "Azerbaijan", iso2: "az", dialCode: "994" },
  { name: "Bosnia and Herzegovina", iso2: "ba", dialCode: "387" },
  { name: "Barbados", iso2: "bb", dialCode: "1-246" },
  { name: "Bangladesh", iso2: "bd", dialCode: "880" },
  { name: "Belgium", iso2: "be", dialCode: "32" },
  { name: "Burkina Faso", iso2: "bf", dialCode: "226" },
  { name: "Bulgaria", iso2: "bg", dialCode: "359" },
  { name: "Bahrain", iso2: "bh", dialCode: "973" },
  { name: "Burundi", iso2: "bi", dialCode: "257" },
  { name: "Benin", iso2: "bj", dialCode: "229" },
  { name: "Saint Barthélemy", iso2: "bl", dialCode: "590" },
  { name: "Bermuda", iso2: "bm", dialCode: "1-441" },
  { name: "Brunei", iso2: "bn", dialCode: "673" },
  { name: "Bolivia", iso2: "bo", dialCode: "591" },
  { name: "Bonaire, Sint Eustatius and Saba", iso2: "bq", dialCode: "599" },
  { name: "Brazil", iso2: "br", dialCode: "55" },
  { name: "Bahamas", iso2: "bs", dialCode: "1-242" },
  { name: "Bhutan", iso2: "bt", dialCode: "975" },
  { name: "Bouvet Island", iso2: "bv", dialCode: "47" },
  { name: "Botswana", iso2: "bw", dialCode: "267" },
  { name: "Belarus", iso2: "by", dialCode: "375" },
  { name: "Belize", iso2: "bz", dialCode: "501" },
  { name: "Canada", iso2: "ca", dialCode: "1" },
  { name: "Cocos (Keeling) Islands", iso2: "cc", dialCode: "61" },
  { name: "Democratic Republic of the Congo", iso2: "cd", dialCode: "243" },
  { name: "Central African Republic", iso2: "cf", dialCode: "236" },
  { name: "Republic of the Congo", iso2: "cg", dialCode: "242" },
  { name: "Switzerland", iso2: "ch", dialCode: "41" },
  { name: "Côte d'Ivoire", iso2: "ci", dialCode: "225" },
  { name: "Cook Islands", iso2: "ck", dialCode: "682" },
  { name: "Chile", iso2: "cl", dialCode: "56" },
  { name: "Cameroon", iso2: "cm", dialCode: "237" },
  { name: "China", iso2: "cn", dialCode: "86" },
  { name: "Colombia", iso2: "co", dialCode: "57" },
  { name: "Costa Rica", iso2: "cr", dialCode: "506" },
  { name: "Cuba", iso2: "cu", dialCode: "53" },
  { name: "Cape Verde", iso2: "cv", dialCode: "238" },
  { name: "Curaçao", iso2: "cw", dialCode: "599" },
  { name: "Christmas Island", iso2: "cx", dialCode: "61" },
  { name: "Cyprus", iso2: "cy", dialCode: "357" },
  { name: "Czech Republic", iso2: "cz", dialCode: "420" },
  { name: "Germany", iso2: "de", dialCode: "49" },
  { name: "Djibouti", iso2: "dj", dialCode: "253" },
  { name: "Denmark", iso2: "dk", dialCode: "45" },
  { name: "Dominica", iso2: "dm", dialCode: "1-767" },
  { name: "Dominican Republic", iso2: "do", dialCode: "1-809" },
  { name: "Algeria", iso2: "dz", dialCode: "213" },
  { name: "Ecuador", iso2: "ec", dialCode: "593" },
  { name: "Estonia", iso2: "ee", dialCode: "372" },
  { name: "Egypt", iso2: "eg", dialCode: "20" },
  { name: "Western Sahara", iso2: "eh", dialCode: "212" },
  { name: "Eritrea", iso2: "er", dialCode: "291" },
  { name: "Spain", iso2: "es", dialCode: "34" },
  { name: "Ethiopia", iso2: "et", dialCode: "251" },
  { name: "Finland", iso2: "fi", dialCode: "358" },
  { name: "Fiji", iso2: "fj", dialCode: "679" },
  { name: "Falkland Islands", iso2: "fk", dialCode: "500" },
  { name: "Micronesia", iso2: "fm", dialCode: "691" },
  { name: "Faroe Islands", iso2: "fo", dialCode: "298" },
  { name: "France", iso2: "fr", dialCode: "33" },
  { name: "Gabon", iso2: "ga", dialCode: "241" },
  { name: "United Kingdom", iso2: "gb", dialCode: "44" },
  { name: "Grenada", iso2: "gd", dialCode: "1-473" },
  { name: "Georgia", iso2: "ge", dialCode: "995" },
  { name: "French Guiana", iso2: "gf", dialCode: "594" },
  { name: "Guernsey", iso2: "gg", dialCode: "44" },
  { name: "Ghana", iso2: "gh", dialCode: "233" },
  { name: "Gibraltar", iso2: "gi", dialCode: "350" },
  { name: "Greenland", iso2: "gl", dialCode: "299" },
  { name: "Gambia", iso2: "gm", dialCode: "220" },
  { name: "Guinea", iso2: "gn", dialCode: "224" },
  { name: "Guadeloupe", iso2: "gp", dialCode: "590" },
  { name: "Equatorial Guinea", iso2: "gq", dialCode: "240" },
  { name: "Greece", iso2: "gr", dialCode: "30" },
  { name: "South Georgia and the South Sandwich Islands", iso2: "gs", dialCode: "500" },
  { name: "Guatemala", iso2: "gt", dialCode: "502" },
  { name: "Guam", iso2: "gu", dialCode: "1-671" },
  { name: "Guinea-Bissau", iso2: "gw", dialCode: "245" },
  { name: "Guyana", iso2: "gy", dialCode: "592" },
  { name: "Hong Kong", iso2: "hk", dialCode: "852" },
  { name: "Heard Island and McDonald Islands", iso2: "hm", dialCode: "672" },
  { name: "Honduras", iso2: "hn", dialCode: "504" },
  { name: "Croatia", iso2: "hr", dialCode: "385" },
  { name: "Haiti", iso2: "ht", dialCode: "509" },
  { name: "Hungary", iso2: "hu", dialCode: "36" },
  { name: "Indonesia", iso2: "id", dialCode: "62" },
  { name: "Ireland", iso2: "ie", dialCode: "353" },
  { name: "Israel", iso2: "il", dialCode: "972" },
  { name: "Isle of Man", iso2: "im", dialCode: "44" },
  { name: "India", iso2: "in", dialCode: "91" },
  { name: "British Indian Ocean Territory", iso2: "io", dialCode: "246" },
  { name: "Iraq", iso2: "iq", dialCode: "964" },
  { name: "Iran", iso2: "ir", dialCode: "98" },
  { name: "Iceland", iso2: "is", dialCode: "354" },
  { name: "Italy", iso2: "it", dialCode: "39" },
  { name: "Jersey", iso2: "je", dialCode: "44" },
  { name: "Jamaica", iso2: "jm", dialCode: "1-876" },
  { name: "Jordan", iso2: "jo", dialCode: "962" },
  { name: "Japan", iso2: "jp", dialCode: "81" },
  { name: "Kenya", iso2: "ke", dialCode: "254" },
  { name: "Kyrgyzstan", iso2: "kg", dialCode: "996" },
  { name: "Cambodia", iso2: "kh", dialCode: "855" },
  { name: "Kiribati", iso2: "ki", dialCode: "686" },
  { name: "Comoros", iso2: "km", dialCode: "269" },
  { name: "Saint Kitts and Nevis", iso2: "kn", dialCode: "1-869" },
  { name: "North Korea", iso2: "kp", dialCode: "850" },
  { name: "South Korea", iso2: "kr", dialCode: "82" },
  { name: "Kuwait", iso2: "kw", dialCode: "965" },
  { name: "Cayman Islands", iso2: "ky", dialCode: "1-345" },
  { name: "Kazakhstan", iso2: "kz", dialCode: "7" },
  { name: "Laos", iso2: "la", dialCode: "856" },
  { name: "Lebanon", iso2: "lb", dialCode: "961" },
  { name: "Saint Lucia", iso2: "lc", dialCode: "1-758" },
  { name: "Liechtenstein", iso2: "li", dialCode: "423" },
  { name: "Sri Lanka", iso2: "lk", dialCode: "94" },
  { name: "Liberia", iso2: "lr", dialCode: "231" },
  { name: "Lesotho", iso2: "ls", dialCode: "266" },
  { name: "Lithuania", iso2: "lt", dialCode: "370" },
  { name: "Luxembourg", iso2: "lu", dialCode: "352" },
  { name: "Latvia", iso2: "lv", dialCode: "371" },
  { name: "Libya", iso2: "ly", dialCode: "218" },
  { name: "Morocco", iso2: "ma", dialCode: "212" },
  { name: "Monaco", iso2: "mc", dialCode: "377" },
  { name: "Moldova", iso2: "md", dialCode: "373" },
  { name: "Montenegro", iso2: "me", dialCode: "382" },
  { name: "Saint Martin", iso2: "mf", dialCode: "590" },
  { name: "Madagascar", iso2: "mg", dialCode: "261" },
  { name: "Marshall Islands", iso2: "mh", dialCode: "692" },
  { name: "North Macedonia", iso2: "mk", dialCode: "389" },
  { name: "Mali", iso2: "ml", dialCode: "223" },
  { name: "Myanmar", iso2: "mm", dialCode: "95" },
  { name: "Mongolia", iso2: "mn", dialCode: "976" },
  { name: "Macao", iso2: "mo", dialCode: "853" },
  { name: "Northern Mariana Islands", iso2: "mp", dialCode: "1-670" },
  { name: "Martinique", iso2: "mq", dialCode: "596" },
  { name: "Mauritania", iso2: "mr", dialCode: "222" },
  { name: "Montserrat", iso2: "ms", dialCode: "1-664" },
  { name: "Malta", iso2: "mt", dialCode: "356" },
  { name: "Mauritius", iso2: "mu", dialCode: "230" },
  { name: "Maldives", iso2: "mv", dialCode: "960" },
  { name: "Malawi", iso2: "mw", dialCode: "265" },
  { name: "Mexico", iso2: "mx", dialCode: "52" },
  { name: "Malaysia", iso2: "my", dialCode: "60" },
  { name: "Mozambique", iso2: "mz", dialCode: "258" },
  { name: "Namibia", iso2: "na", dialCode: "264" },
  { name: "New Caledonia", iso2: "nc", dialCode: "687" },
  { name: "Niger", iso2: "ne", dialCode: "227" },
  { name: "Norfolk Island", iso2: "nf", dialCode: "672" },
  { name: "Nigeria", iso2: "ng", dialCode: "234" },
  { name: "Nicaragua", iso2: "ni", dialCode: "505" },
  { name: "Netherlands", iso2: "nl", dialCode: "31" },
  { name: "Norway", iso2: "no", dialCode: "47" },
  { name: "Nepal", iso2: "np", dialCode: "977" },
  { name: "Nauru", iso2: "nr", dialCode: "674" },
  { name: "Niue", iso2: "nu", dialCode: "683" },
  { name: "New Zealand", iso2: "nz", dialCode: "64" },
  { name: "Oman", iso2: "om", dialCode: "968" },
  { name: "Panama", iso2: "pa", dialCode: "507" },
  { name: "Peru", iso2: "pe", dialCode: "51" },
  { name: "French Polynesia", iso2: "pf", dialCode: "689" },
  { name: "Papua New Guinea", iso2: "pg", dialCode: "675" },
  { name: "Philippines", iso2: "ph", dialCode: "63" },
  { name: "Pakistan", iso2: "pk", dialCode: "92" },
  { name: "Poland", iso2: "pl", dialCode: "48" },
  { name: "Saint Pierre and Miquelon", iso2: "pm", dialCode: "508" },
  { name: "Pitcairn Islands", iso2: "pn", dialCode: "64" },
  { name: "Puerto Rico", iso2: "pr", dialCode: "1-787" },
  { name: "Palestine", iso2: "ps", dialCode: "970" },
  { name: "Portugal", iso2: "pt", dialCode: "351" },
  { name: "Palau", iso2: "pw", dialCode: "680" },
  { name: "Paraguay", iso2: "py", dialCode: "595" },
  { name: "Qatar", iso2: "qa", dialCode: "974" },
  { name: "Réunion", iso2: "re", dialCode: "262" },
  { name: "Romania", iso2: "ro", dialCode: "40" },
  { name: "Serbia", iso2: "rs", dialCode: "381" },
  { name: "Russia", iso2: "ru", dialCode: "7" },
  { name: "Rwanda", iso2: "rw", dialCode: "250" },
  { name: "Saudi Arabia", iso2: "sa", dialCode: "966" },
  { name: "Solomon Islands", iso2: "sb", dialCode: "677" },
  { name: "Seychelles", iso2: "sc", dialCode: "248" },
  { name: "Sudan", iso2: "sd", dialCode: "249" },
  { name: "Sweden", iso2: "se", dialCode: "46" },
  { name: "Singapore", iso2: "sg", dialCode: "65" },
  { name: "Saint Helena", iso2: "sh", dialCode: "290" },
  { name: "Slovenia", iso2: "si", dialCode: "386" },
  { name: "Svalbard and Jan Mayen", iso2: "sj", dialCode: "47" },
  { name: "Slovakia", iso2: "sk", dialCode: "421" },
  { name: "Sierra Leone", iso2: "sl", dialCode: "232" },
  { name: "San Marino", iso2: "sm", dialCode: "378" },
  { name: "Senegal", iso2: "sn", dialCode: "221" },
  { name: "Somalia", iso2: "so", dialCode: "252" },
  { name: "Suriname", iso2: "sr", dialCode: "597" },
  { name: "South Sudan", iso2: "ss", dialCode: "211" },
  { name: "São Tomé and Príncipe", iso2: "st", dialCode: "239" },
  { name: "El Salvador", iso2: "sv", dialCode: "503" },
  { name: "Sint Maarten", iso2: "sx", dialCode: "1-721" },
  { name: "Syria", iso2: "sy", dialCode: "963" },
  { name: "Eswatini", iso2: "sz", dialCode: "268" },
  { name: "Turks and Caicos Islands", iso2: "tc", dialCode: "1-649" },
  { name: "Chad", iso2: "td", dialCode: "235" },
  { name: "French Southern Territories", iso2: "tf", dialCode: "262" },
  { name: "Togo", iso2: "tg", dialCode: "228" },
  { name: "Thailand", iso2: "th", dialCode: "66" },
  { name: "Tajikistan", iso2: "tj", dialCode: "992" },
  { name: "Tokelau", iso2: "tk", dialCode: "690" },
  { name: "Timor-Leste", iso2: "tl", dialCode: "670" },
  { name: "Turkmenistan", iso2: "tm", dialCode: "993" },
  { name: "Tunisia", iso2: "tn", dialCode: "216" },
  { name: "Tonga", iso2: "to", dialCode: "676" },
  { name: "Turkey", iso2: "tr", dialCode: "90" },
  { name: "Trinidad and Tobago", iso2: "tt", dialCode: "1-868" },
  { name: "Tuvalu", iso2: "tv", dialCode: "688" },
  { name: "Taiwan", iso2: "tw", dialCode: "886" },
  { name: "Tanzania", iso2: "tz", dialCode: "255" },
  { name: "Ukraine", iso2: "ua", dialCode: "380" },
  { name: "Uganda", iso2: "ug", dialCode: "256" },
  { name: "United States Minor Outlying Islands", iso2: "um", dialCode: "1" },
  { name: "United States", iso2: "us", dialCode: "1" },
  { name: "Uruguay", iso2: "uy", dialCode: "598" },
  { name: "Uzbekistan", iso2: "uz", dialCode: "998" },
  { name: "Vatican City", iso2: "va", dialCode: "39" },
  { name: "Saint Vincent and the Grenadines", iso2: "vc", dialCode: "1-784" },
  { name: "Venezuela", iso2: "ve", dialCode: "58" },
  { name: "British Virgin Islands", iso2: "vg", dialCode: "1-284" },
  { name: "U.S. Virgin Islands", iso2: "vi", dialCode: "1-340" },
  { name: "Vietnam", iso2: "vn", dialCode: "84" },
  { name: "Vanuatu", iso2: "vu", dialCode: "678" },
  { name: "Wallis and Futuna", iso2: "wf", dialCode: "681" },
  { name: "Samoa", iso2: "ws", dialCode: "685" },
  { name: "Yemen", iso2: "ye", dialCode: "967" },
  { name: "Mayotte", iso2: "yt", dialCode: "262" },
  { name: "South Africa", iso2: "za", dialCode: "27" },
  { name: "Zambia", iso2: "zm", dialCode: "260" },
  { name: "Zimbabwe", iso2: "zw", dialCode: "263" },
];
